name: Test1
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  printLog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print log
        run: echo "Hello World"
